In [1]:
import numpy as np

In [2]:
# Create Numpy array
# range ( get a sequence of numbers )
# arange ( gets array of numbers ) compatiable with np

range_nparray = np.array(range(1,200))
arange_nparray = np.arange(1,200)

In [3]:
range_nparray

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [4]:
arange_nparray

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [5]:
# Create zeros numpy array
zeros_nparray = np.zeros(10)

In [6]:
zeros_nparray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Create ones numpy array
ones_nparray = np.ones(20)

In [8]:
ones_nparray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [9]:
# Create empty numpy array
empty_nparray = np.empty(15)

In [10]:
empty_nparray

array([4.81598192e-310, 0.00000000e+000, 6.85271996e-310, 6.85271984e-310,
       6.85271984e-310, 6.85271982e-310, 6.85271999e-310, 6.85271996e-310,
       6.85271999e-310, 6.85271984e-310, 6.85269890e-310, 1.63041663e-322,
       4.81481972e-310, 6.85272027e-310, 6.32404027e-322])

In [11]:
# Create linear space numpy array
linear_nparray = np.linspace(0,20,5)

In [12]:
linear_nparray

array([ 0.,  5., 10., 15., 20.])

In [13]:
# Sort Numpy array
np.sort(empty_nparray)

array([0.00000000e+000, 1.63041663e-322, 6.32404027e-322, 4.81481972e-310,
       4.81598192e-310, 6.85269890e-310, 6.85271982e-310, 6.85271984e-310,
       6.85271984e-310, 6.85271984e-310, 6.85271996e-310, 6.85271996e-310,
       6.85271999e-310, 6.85271999e-310, 6.85272027e-310])

In [14]:
# Concatenate 2 numpy array
np.sort(np.concatenate((np.ones(10),np.empty(25))))

array([0.00000000e+000, 1.41500401e-320, 4.81598119e-310, 6.85270020e-310,
       6.85270020e-310, 6.85271996e-310, 6.85271996e-310, 6.85271996e-310,
       6.85271996e-310, 6.85271996e-310, 6.85271996e-310, 6.85271996e-310,
       6.85271996e-310, 6.85271996e-310, 6.85271996e-310, 6.85271996e-310,
       6.85271996e-310, 6.85271996e-310, 6.85271996e-310, 6.85271996e-310,
       6.85271996e-310, 6.85271996e-310, 6.85271996e-310, 6.85271996e-310,
       6.85272000e-310, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
       1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
       1.00000000e+000, 1.00000000e+000, 1.00000000e+000])

In [15]:
# Reshaping the array
onedim_nparray = np.ones(720)

In [16]:
onedim_nparray.ndim

1

In [17]:
# Reshape one dimensional array
twodim_nparray = onedim_nparray.reshape(72,10)

In [18]:
# Obtain dimension of array
twodim_nparray.ndim

2

In [19]:
# Obtain shape of numpy array
twodim_nparray.shape

(72, 10)

In [20]:
# Flatten numpy array
twodim_nparray.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [21]:
# create multidimension array
twodim_nparray.flatten().reshape(10,9,2,4).ndim

4

In [22]:
# create multidimension array
multidim_array = twodim_nparray.flatten().reshape(10,9,2,4)

In [23]:
multidim_array[0]

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
# Manipulation on nparray
manipulate_nparray = np.arange(1,99)

In [25]:
# !!! Important , internally numpy creates array of boolean value

boolean_array = (manipulate_nparray < 10) | (manipulate_nparray > 30)

In [26]:
manipulate_nparray[boolean_array]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
multidim_manipulate_nparray = np.arange(0,100).reshape(10,5,2)

In [28]:
multi_boolean_array = (multidim_manipulate_nparray < 10) | (multidim_manipulate_nparray > 30)

In [29]:
multidim_manipulate_nparray[multi_boolean_array]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
       89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
# Capture the indices
np.nonzero(multidim_manipulate_nparray == 3)

(array([0]), array([1]), array([1]))

In [31]:
multidim_manipulate_nparray[0,1,1]

3

In [32]:
# Capture indices in readable format

indices_multidim = np.nonzero(multidim_manipulate_nparray < 10)

In [33]:
indices_readable_format = list(zip(indices_multidim[0],indices_multidim[1],indices_multidim [2]))

In [34]:
indices_readable_format

[(0, 0, 0),
 (0, 0, 1),
 (0, 1, 0),
 (0, 1, 1),
 (0, 2, 0),
 (0, 2, 1),
 (0, 3, 0),
 (0, 3, 1),
 (0, 4, 0),
 (0, 4, 1)]

In [35]:
for value in indices_readable_format:
  print(value)

(0, 0, 0)
(0, 0, 1)
(0, 1, 0)
(0, 1, 1)
(0, 2, 0)
(0, 2, 1)
(0, 3, 0)
(0, 3, 1)
(0, 4, 0)
(0, 4, 1)


In [36]:
# Operation Addtion

indices_multidim[0] + indices_multidim[1]

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [37]:
# Mulitplication

indices_multidim[0] * indices_multidim[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
# Division ( * trying to divide with zero)

indices_multidim[0] / indices_multidim[1]

<ipython-input-38-89f43284a613>:3: RuntimeWarning: invalid value encountered in divide
  indices_multidim[0] / indices_multidim[1]


array([nan, nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [39]:
multidim_manipulate_nparray.sum()

4950

In [40]:
multidim_manipulate_nparray.shape

(10, 5, 2)

In [41]:
multidim_manipulate_nparray

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69]],

       [[70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89]],

       [[90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [42]:
# Used in Feature Engineering , retain the column and column wise sum up
multidim_manipulate_nparray.sum(axis=0)

array([[450, 460],
       [470, 480],
       [490, 500],
       [510, 520],
       [530, 540]])

In [43]:
multidim_manipulate_nparray.sum(axis=1)

array([[ 20,  25],
       [ 70,  75],
       [120, 125],
       [170, 175],
       [220, 225],
       [270, 275],
       [320, 325],
       [370, 375],
       [420, 425],
       [470, 475]])

In [44]:
multidim_manipulate_nparray.sum(axis=2)

array([[  1,   5,   9,  13,  17],
       [ 21,  25,  29,  33,  37],
       [ 41,  45,  49,  53,  57],
       [ 61,  65,  69,  73,  77],
       [ 81,  85,  89,  93,  97],
       [101, 105, 109, 113, 117],
       [121, 125, 129, 133, 137],
       [141, 145, 149, 153, 157],
       [161, 165, 169, 173, 177],
       [181, 185, 189, 193, 197]])

In [45]:
multidim_manipulate_nparray.max(axis=0)

array([[90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [46]:
multidim_manipulate_nparray.min(axis=1)

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51],
       [60, 61],
       [70, 71],
       [80, 81],
       [90, 91]])

In [47]:
# To generate random numbers for numpy array
random_generator = np.random.default_rng()

In [48]:
random_generator.random(10)

array([0.60807174, 0.77541182, 0.43204228, 0.8861464 , 0.58273463,
       0.52347549, 0.09537464, 0.37819195, 0.45407935, 0.95987356])

In [49]:
non_unique = np.ones(100)

In [50]:
# Obtain unique values and count

np.unique(non_unique,return_counts=True)

(array([1.]), array([100]))

In [51]:
multidim_manipulate_nparray.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [52]:
# Transpose an array
multidim_manipulate_nparray.T.shape

(2, 5, 10)

In [53]:
multidim_manipulate_nparray.shape

(10, 5, 2)

In [54]:
np.flip(multidim_manipulate_nparray,axis=2)

array([[[ 1,  0],
        [ 3,  2],
        [ 5,  4],
        [ 7,  6],
        [ 9,  8]],

       [[11, 10],
        [13, 12],
        [15, 14],
        [17, 16],
        [19, 18]],

       [[21, 20],
        [23, 22],
        [25, 24],
        [27, 26],
        [29, 28]],

       [[31, 30],
        [33, 32],
        [35, 34],
        [37, 36],
        [39, 38]],

       [[41, 40],
        [43, 42],
        [45, 44],
        [47, 46],
        [49, 48]],

       [[51, 50],
        [53, 52],
        [55, 54],
        [57, 56],
        [59, 58]],

       [[61, 60],
        [63, 62],
        [65, 64],
        [67, 66],
        [69, 68]],

       [[71, 70],
        [73, 72],
        [75, 74],
        [77, 76],
        [79, 78]],

       [[81, 80],
        [83, 82],
        [85, 84],
        [87, 86],
        [89, 88]],

       [[91, 90],
        [93, 92],
        [95, 94],
        [97, 96],
        [99, 98]]])

In [55]:
np.sort(np.flip(multidim_manipulate_nparray,axis=2).flatten())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [56]:
multidim_array?

In [57]:
len??